version: '3.5'
services:
    json-server:
      image: vimagick/json-server
      command: -H 0.0.0.0 -p 3000 -w heroes.json
      ports:
        - "3000:3000"
      container_name: json-server
      hostname: json-server
      volumes: 
         - './src/assets/db:/data'
      networks:
        - some-net 
    angular-service: 
      container_name: angular-service
      build:      
        context: .
        dockerfile: Dockerfile
      volumes:
        - '.:/usr/src/app' 
      ports: 
        - '4200:4200'
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
networks:
  some-net:
    driver: bridge        